# Generated by Django 3.2.9 on 2022-11-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentario', models.TextField(blank=True, max_length=180, null=True)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'db_table': 'convenio',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Familia Animal',
                'verbose_name_plural': 'Familias Animales',
                'db_table': 'familias animales',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=6)),
                ('polaridad', models.CharField(max_length=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comentario', models.TextField(blank=True, max_length=180, null=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.familia')),
            ],
            options={
                'verbose_name': 'Genero Animal',
                'verbose_name_plural': 'Generos Animales',
                'db_table': 'generos animales',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.genero')),
            ],
            options={
                'verbose_name': 'Especie Animal',
                'verbose_name_plural': 'Especies Animales',
                'db_table': 'especies animales',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('repositorio', models.CharField(max_length=40)),
                ('fecha_colecta', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_alt', models.CharField(max_length=10)),
                ('comentario', models.TextField(blank=True, max_length=180, null=True)),
                ('convenio', models.ManyToManyField(to='Animales.Convenio')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.especie')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.familia')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.genero')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.localidad')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'animales',
            },
        ),
    ]
