# Generated by Django 3.2.9 on 2022-11-25 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Especie Planta',
                'verbose_name_plural': 'Especies Plantas',
                'db_table': 'especies plantas',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Familia Planta',
                'verbose_name_plural': 'Familias Plantas',
                'db_table': 'familias plantas',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.familia')),
            ],
            options={
                'verbose_name': 'Genero Planta',
                'verbose_name_plural': 'Generos Plantas',
                'db_table': 'generos plantas',
            },
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=7)),
                ('nombre', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Locacion',
                'verbose_name_plural': 'Locaciones',
                'db_table': 'locaciones',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_coleccion', models.DateTimeField()),
                ('importancia', models.CharField(max_length=40)),
                ('medidas', models.CharField(max_length=40)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.especie')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.familia')),
                ('foto', models.ManyToManyField(blank=True, to='Plantas.Foto')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.genero')),
                ('locacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.locacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.tipo')),
                ('unidades_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.unidadesmedida')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'plantas',
            },
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantas.genero'),
        ),
    ]
